# Generated by Django 3.0.3 on 2020-02-17 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=150)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ENGLISH', 'English'), ('SPANISH', 'Spanish'), ('FRENCH', 'French'), ('GERMANY', 'Germany')], default='ENGLISH', max_length=12)),
                ('own_level_of_language', models.CharField(choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('PRE_INTERMEDIATE', 'Pre-Intermediate'), ('INTERMEDIATE', 'Intermediate'), ('UPPER_INTERMEDIATE', 'Upper-Intermediate'), ('ADVANCE', 'Advance')], max_length=20)),
                ('level_of_training', multiselectfield.db.fields.MultiSelectField(choices=[('BEGINNER', 'Beginner'), ('ELEMENTARY', 'Elementary'), ('PRE_INTERMEDIATE', 'Pre-Intermediate'), ('INTERMEDIATE', 'Intermediate'), ('UPPER_INTERMEDIATE', 'Upper-Intermediate'), ('ADVANCE', 'Advance')], max_length=76)),
                ('days_of_work', multiselectfield.db.fields.MultiSelectField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=56)),
                ('types_of_lesson', multiselectfield.db.fields.MultiSelectField(choices=[('ZNO', 'ZNO'), ('SPEAKING', 'Speaking'), ('BUSINESS', 'Business'), ('TRAVELING', 'Traveling')], max_length=31)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skype_eng_learning.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skype_eng_learning.Profile')),
            ],
        ),
    ]
